# starts pieval webapp and associated mongo container - in a production mode
# NOT using the Flask dev server, instead using gunicorn wsgi server
# Persists data by using a bind mount with the mongo container - see docs/README_persistence.md for more information

version: "3.8"

networks:
  net_pv:

services:
  pieval:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5001:5001"
    volumes:
      - .:/pieval
    networks: 
      - net_pv
    command: gunicorn --preload -w 4 -b 0.0.0.0:5001 "app.wsgi:create_app()"
    depends_on:
      - mongo
  mongo:
    restart: always
    image: mongo:6
    networks:
      - net_pv
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db